services:
  jvm-quarkus:
    image: docker.io/adrianomoreira86/crud-quarkus-jvm:latest
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: 123
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/rinha
      QUARKUS_DATASOURCE_JDBC_MAX-SIZE: 16
      QUARKUS_REDIS_HOSTS: redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "512MB"

  db:
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ../script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: "1024MB"
  redis:
    image: redis:7.4-alpine
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1024MB"