services:

  deno-nestjs-app:
    image: docker.io/adrianomoreira86/deno-nestjs-app:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATASOURCE_HOST: db
      DATASOURCE_PORT: 5432
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: 123
      DATASOURCE_DATABASE: rinha
      DATASOURCE_POLL_SIZE: 8 #2 replicas
      REDIS_CONNECTION_STRING: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      replicas: 2
      endpoint_mode: vip
      resources:
        limits:
          cpus: "1.0" #2 replicas
          memory: "256MB" #2 replicas
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ../script.sql:/docker-entrypoint-initdb.d/script.sql:ro
      # - /dev/shm/pgdata:/var/lib/postgresql/data:rw
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: "1024MB"
  redis:
    image: redis:7.4-alpine
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1024MB"
